import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Provider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-end items-center p-4 gap-4 h-16">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-black text-white rounded-full font-medium text-xs sm:text-sm h-6 sm:h-9 px-3 sm:px-4 cursor-pointer transition-all duration-300 btn-animate">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton>
                <button className="bg-grey text-white rounded-full font-medium text-xs sm:text-sm h-6 sm:h-9 px-3 sm:px-4 cursor-pointer transition-all duration-300 btn-animate">
                  Sign In
                </button>
              </UserButton>
            </SignedIn>
          </header>
          <Provider>{children}</Provider>
          
        </body>
      </html>
    </ClerkProvider>
  );
}
